GEMINI_API_KEY = "AIzaSyC2JpLpiqgnaH1BgL_-FTimpglTCxg45Dc"
EMAIL_PASS_TSHREE = "pcxkzqekbymmpywi"
EMAIL_PASS_VIS = "jpprsezowjfabtdi"
EMAIL_PASS_SPHALGUNA = "qncwrnpbetipmxvx"
EMAIL_PASS_MOHIT = "xbgohksvkgvslisv"
EMAIL_PASS_SN = "syltqmkdhwdemway"
EMAIL_PASS_MANJUSHREE = "skrdbhwptqxjtyte"